"""create_regulatory_audit_logs_table

Revision ID: 40db6b5d0c46
Revises: 
Create Date: 2026-06-02 19:46:02.309328

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision: str = '40db6b5d0c46'
down_revision: Union[str, None] = None
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('regulatory_audit_logs',
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('timestamp', sa.DateTime(timezone=True), nullable=False),
    sa.Column('event_type', sa.String(length=50), nullable=False),
    sa.Column('source_service', sa.String(length=100), nullable=False),
    sa.Column('actor', sa.String(length=100), nullable=False),
    sa.Column('payload', postgresql.JSONB(astext_type=sa.Text()), nullable=False),
    sa.Column('hash_signature', sa.String(length=64), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_regulatory_audit_logs_event_type'), 'regulatory_audit_logs', ['event_type'], unique=False)
    op.create_index(op.f('ix_regulatory_audit_logs_timestamp'), 'regulatory_audit_logs', ['timestamp'], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_regulatory_audit_logs_timestamp'), table_name='regulatory_audit_logs')
    op.drop_index(op.f('ix_regulatory_audit_logs_event_type'), table_name='regulatory_audit_logs')
    op.drop_table('regulatory_audit_logs')
    # ### end Alembic commands ###
