"""create_regulatory_audit_logs_table2

Revision ID: 560cd7cc1687
Revises: 40db6b5d0c46
Create Date: 2026-06-02 19:49:33.724603

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '560cd7cc1687'
down_revision: Union[str, None] = '40db6b5d0c46'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###
